### ISSUE TITLE
Linux: keyboard shortcut conflict.

### ISSUE THREAD

**Issue by GravisZro** [jamiely/citethis#25]
You have assigned the sidebar to being ctrl+shift+y but that is [the keyboard shortcut for "Downloads" on Linux](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).

I recommend making this an assignable key combo or adding the ability to bring it up by using a button (e.g. in the overflow menu).

**Comment by SalaKrisztian** [comment]
Completely agree with this

**Comment by krisztiansala** [comment]
Created a PR for it https://github.com/jamiely/citethis/pull/26
