### ISSUE TITLE
Unable to locate the installed/active Cithethis icon in Firefox Menu Bar

### ISSUE THREAD

**Issue by paulindr** [jamiely/citethis#7]
Hi. I've used Citethis for quite a while in 2019 and probably before. Suddenly, I cannot find the icon with which to open the extension (i.e. to command the app to offer a citation for a webpage). I'm unaware of any action (such as a Firefox upgrade) that caused this. The menu bar (normal) does not show the icon (see attached image) though it does show 8 other icons for extensions I have personally installed). It shows no icons at all in the overflow menu (so there is no double right arrow symbol by which to access the overflow. 
![Citethis (1)](https://user-images.githubusercontent.com/59750662/72192714-f4bbee00-33dc-11ea-98ec-9449908425ba.JPG)

The Citethis extension is shown as installed and permitted.

I have uninstalled Citethis and reinstalled it and it still will not reveal the icon in the menubar. I have restarted Firefox and still the icon is absent.

I am working on a Windows Laptop. Windows 10 Home (currently v1903  18362.535)) is fully up to date and Firefox is always the most recent (currently 72.0.1  64-bit) and up to date version. 

Thanks if you can help resolve accessing Citethis.

**Comment by jamiely** [comment]
* Open the CiteThis! Sidebar from View > Sidebar > CiteThis!
  * On Windows, you might have to press the ALT key to see the View menu.
  * On Windows, you may need to click the Show Sidebars icon at the top right.

**Comment by paulindr** [comment]
Thank you for the reply.

Regrettably, I don't understand it at all. (I'm not generally inexperienced
with IT but maybe I'm just being dumb on this point.)

I have no idea where to locate a CiteThis! sidebar. or anything that opens
one.
I generally use the Firefox browser and
 I'm working on a Windows 10 laptop. The only sidebar I can open is the
Bookmarks sidebar but that contains nothing related to citeThis!,as far as
I can see.

I have no idea where to find a View menu. Clicking the ALT key doesn't help.

Paul Temple
